version: "3"
services:
    web:
        build: Dockerfile
        context: .
        ports:
            - "5001:5001"
            - "5000:5000"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - '1433:1433'
        volumes:
            - './mysql_data:/var/opt/mssql/data'
        environment:
            SA_PASSWORD: "P@ssw0rd"
            ACCEPT_EULA: Y